### PR TITLE
add Types Folder to Export-RootModule

### PR DESCRIPTION
**Pull request by T0biii**
i want to use your build script for this Repo:
https://github.com/baramundisoftware/PS-bConnect/tree/master/bConnect
which is using custom Types.

The Build process failed because of the types that are missing

### CODE REVIEW

**Comment by codaamok** [comment]
Perhaps might make sense to  also update [New-ModuleDirStructure](https://github.com/codaamok/codaamok.build/blob/main/codaamok.build/Public/Setup/New-ModuleDirStructure.ps1#L44) - could you include that in your fork aswell?

You'll also need to update the changelog, see [CONTRIBUTING.md](https://github.com/codaamok/codaamok.build/blob/main/CONTRIBUTING.md).

**Comment by codaamok** [comment]
As an aside, how did you come across my build script/module?

**Comment by T0biii** [comment]
> As an aside, how did you come across my build script/module?

i saw your Shlink Project (https://github.com/codaamok/PSShlink) using this "Framework" for Auto Publishing

 


> Perhaps might make sense to also update [New-ModuleDirStructure](https://github.com/codaamok/codaamok.build/blob/main/codaamok.build/Public/Setup/New-ModuleDirStructure.ps1?rgh-link-date=2022-01-24T18%3A27%3A30Z#L44) - could you include that in your fork aswell?
> 
> You'll also need to update the changelog, see [CONTRIBUTING.md (https://github.com/codaamok/codaamok.build/blob/main/CONTRIBUTING.md?rgh-link-date=2022-01-24T18%3A27%3A30Z).

I'll look at the other function and also update the Changelog soon.

**Comment by T0biii** [comment]
suppressed by #2

**Pull request closed without merging**
